CREATE TABLE AUTOR (
  NOMBRE_AUT VARCHAR(45),
  APELLIDOS VARCHAR(20),
  PRIMARY KEY(NOMBRE_AUT));

CREATE TABLE EDITORIAL (
  COD_EDIT INT,
  NOMBRE VARCHAR(20),
  PRIMARY KEY(COD_EDIT));

CREATE TABLE GENERO (
  COD_GEN INT,
  NOMBRE VARCHAR(20),
  PRIMARY KEY(COD_GEN));

CREATE TABLE IDIOMA (
  COD_IDI INT,
  NOMBRE VARCHAR(20),
  PRIMARY KEY(COD_IDI));

CREATE TABLE LIBRO (
  NRO_SERIE INT,
  COD_EDIT INT,
  NOMBRE_AUT VARCHAR(45),
  NOMBRE VARCHAR(20),
  COD_GEN INT,
  COD_IDI INT,
  PRECIO INT,
  PRIMARY KEY(NRO_SERIE),
  FOREIGN KEY(NOMBRE_AUT)
    REFERENCES AUTOR(NOMBRE_AUT),
  FOREIGN KEY(COD_IDI)
    REFERENCES IDIOMA(COD_IDI),
  FOREIGN KEY(COD_EDIT)
    REFERENCES EDITORIAL(COD_EDIT),
  FOREIGN KEY(COD_GEN)
    REFERENCES GENERO(COD_GEN));

CREATE TABLE PAIS(
  COD_PAIS INT,
  NOMBRE VARCHAR(20),
  COD_CIU INT,
  PRIMARY KEY(COD_PAIS));

CREATE TABLE CIUDAD(
  COD_CIU INT,
  NOMBRE VARCHAR(20),
  COD_COM INT,
  PRIMARY KEY (COD_CIU));

CREATE TABLE COMUNA(
  COD_COM INT,
  NOMBRE VARCHAR(20),
  PRIMARY KEY(COD_COM));

CREATE TABLE tipo_tel(
  COD_tel INT,
  NOMBRE VARCHAR(20),
  PRIMARY KEY(COD_tel));
  
CREATE TABLE tipo_libro(
  COD_libro INT,
  NOMBRE VARCHAR(20),
  PRIMARY KEY(COD_libro));

CREATE TABLE CONTRATO(
  COD_CONT INT,
  NOMBRE VARCHAR(20),
  FECHA VARCHAR(20),
  PRIMARY KEY(COD_CONT));

CREATE TABLE CLIENTE(
  RUT_CLI VARCHAR(10),
  NOMBRE VARCHAR(30),
  APELLIDOP VARCHAR(20),
  APELLIDOM VARCHAR(20),
  FEC_NAC VARCHAR(20),
  TIPO_TEL INT,
  TELEFONO INT,
  CORREO VARCHAR(20),
  COD_CIU INT,
  PRIMARY KEY(RUT_CLI));
  
CREATE TABLE TRABAJADOR(
  RUT_TRA VARCHAR(10),
  NOMBRE VARCHAR(30),
  APELLIDOP VARCHAR(20),
  APELLIDOM VARCHAR(20),
  FEC_NAC VARCHAR(20),
  TIPO_TEL INT,
  TELEFONO INT,
  CORREO VARCHAR(20),
  COD_CIU INT,
  COD_CONT INT,
  PRIMARY KEY(RUT_TRA));
  
CREATE TABLE DISTRIBUIDOR(
  RUT_DIST VARCHAR(20),
  NOMBRE VARCHAR(30),
  TELEFONO INT,
  COD_IMP INT,
  COD_CIU INT,
  PRIMARY KEY(RUT_DIST));
  
CREATE TABLE FABRICA(
  COD_FABR INT,
  NOMBRE VARCHAR(20),
  PRIMARY KEY (COD_FABR));
  
CREATE TABLE IMPRENTA(
  COD_IMP INT,
  NOMBRE VARCHAR(20),
  COD_PROV INT,
  PRIMARY KEY (COD_IMP));
  
CREATE TABLE PROVEEDOR(
  COD_PROV INT,
  NOMBRE VARCHAR(20),
  COD_FABR INT,
  PRIMARY KEY (COD_PROV)); 
  
ALTER TABLE PROVEEDOR
ADD CONSTANT FK_COD_FABR
FOREIGN KEY (COD_FABR) REFERENCES FABRICA
  
ALTER TABLE IMPRENTA
ADD CONSTANT FK_COD_PROV
FOREIGN KEY (COD_PROV) REFERENCES PROVEEDOR


ALTER TABLE DISTRIBUIDOR
ADD CONSTANT FK_COD_IMP
FOREIGN KEY (COD_IMP) REFERENCES IMPRENTA
  
ALTER TABLE DISTRIBUIDOR
ADD CONSTRAINT FK_COD_IMP
FOREIGN KEY (COD_IMP) REFERENCES IMPRENTA

ALTER TABLE DISTRIBUIDOR
ADD CONSTRAINT FK_COD_CIU
FOREIGN KEY (COD_CIU) REFERENCES CIUDAD

ALTER TABLE TRABAJADOR
ADD CONSTRAINT FK_COD_CIU
FOREIGN KEY (COD_CIU) REFERENCES CIUDAD

ALTER TABLE TRABAJADOR
ADD CONSTRAINT FK_COD_CONT
FOREIGN KEY (COD_CONT) REFERENCES CONTRATO

ALTER TABLE TRABAJADOR
ADD CONSTRAINT FK_COD_TEL
FOREIGN KEY (COD_TEL) REFERENCES TIPO_TEL  
  
ALTER TABLE CLIENTE
ADD CONSTRAINT FK_COD_CIU
FOREIGN KEY (COD_CIU) REFERENCES CIUDAD

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_COD_TEL
FOREIGN KEY (COD_TEL) REFERENCES TIPO_TEL

ALTER TABLE PAIS
ADD CONSTRAINT FK_COD_CIU
FOREIGN KEY (COD_CIU) REFERENCES CIUDAD

ALTER TABLE CIUDAD
ADD CONSTRAINT FK_COD_COM
FOREIGN KEY (COD_COM) REFERENCES COMUNA
	